"""Added Wishlist table

Revision ID: 5cc64e587899
Revises: 78e5b6dbee89
Create Date: 2024-07-13 23:01:21.576419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cc64e587899'
down_revision: Union[str, None] = '78e5b6dbee89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wishlists',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['public.products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['public.user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_wishlists_product_id'), 'wishlists', ['product_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_wishlists_user_id'), 'wishlists', ['user_id'], unique=False, schema='public')
    op.drop_constraint('addresses_user_profile_id_fkey', 'addresses', type_='foreignkey')
    op.create_foreign_key(None, 'addresses', 'user_profiles', ['user_profile_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('inventory_product_id_fkey', 'inventory', type_='foreignkey')
    op.create_foreign_key(None, 'inventory', 'products', ['product_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('product_reviews_user_id_fkey', 'product_reviews', type_='foreignkey')
    op.drop_constraint('product_reviews_product_id_fkey', 'product_reviews', type_='foreignkey')
    op.create_foreign_key(None, 'product_reviews', 'user_profiles', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'product_reviews', 'products', ['product_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('products_category_id_fkey', 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'categories', ['category_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('user_profiles_user_id_fkey', 'user_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'user_profiles', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_profiles', schema='public', type_='foreignkey')
    op.create_foreign_key('user_profiles_user_id_fkey', 'user_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'products', schema='public', type_='foreignkey')
    op.create_foreign_key('products_category_id_fkey', 'products', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'product_reviews', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'product_reviews', schema='public', type_='foreignkey')
    op.create_foreign_key('product_reviews_product_id_fkey', 'product_reviews', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('product_reviews_user_id_fkey', 'product_reviews', 'user_profiles', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'inventory', schema='public', type_='foreignkey')
    op.create_foreign_key('inventory_product_id_fkey', 'inventory', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'addresses', schema='public', type_='foreignkey')
    op.create_foreign_key('addresses_user_profile_id_fkey', 'addresses', 'user_profiles', ['user_profile_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_public_wishlists_user_id'), table_name='wishlists', schema='public')
    op.drop_index(op.f('ix_public_wishlists_product_id'), table_name='wishlists', schema='public')
    op.drop_table('wishlists', schema='public')
    # ### end Alembic commands ###
