"""Added UserProfile Relationships

Revision ID: c50091b63a6d
Revises: 5dce3c1bf396
Create Date: 2024-07-14 09:10:20.485504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c50091b63a6d'
down_revision: Union[str, None] = '5dce3c1bf396'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('addresses_user_profile_id_fkey', 'addresses', type_='foreignkey')
    op.create_foreign_key(None, 'addresses', 'user_profiles', ['user_profile_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('cart_items_cart_id_fkey', 'cart_items', type_='foreignkey')
    op.drop_constraint('cart_items_product_id_fkey', 'cart_items', type_='foreignkey')
    op.create_foreign_key(None, 'cart_items', 'carts', ['cart_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'cart_items', 'products', ['product_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('carts_user_id_fkey', 'carts', type_='foreignkey')
    op.drop_constraint('carts_product_id_fkey', 'carts', type_='foreignkey')
    op.create_foreign_key(None, 'carts', 'user_profiles', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'carts', 'products', ['product_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('inventory_product_id_fkey', 'inventory', type_='foreignkey')
    op.create_foreign_key(None, 'inventory', 'products', ['product_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('orders_user_id_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'user_profiles', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('payments_user_id_fkey', 'payments', type_='foreignkey')
    op.drop_constraint('payments_order_id_fkey', 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'orders', ['order_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'payments', 'user_profiles', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('product_reviews_user_id_fkey', 'product_reviews', type_='foreignkey')
    op.drop_constraint('product_reviews_product_id_fkey', 'product_reviews', type_='foreignkey')
    op.create_foreign_key(None, 'product_reviews', 'products', ['product_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'product_reviews', 'user_profiles', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('products_category_id_fkey', 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'categories', ['category_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('user_profiles_user_id_fkey', 'user_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'user_profiles', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('wishlists_user_id_fkey', 'wishlists', type_='foreignkey')
    op.drop_constraint('wishlists_product_id_fkey', 'wishlists', type_='foreignkey')
    op.create_foreign_key(None, 'wishlists', 'user_profiles', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'wishlists', 'products', ['product_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wishlists', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'wishlists', schema='public', type_='foreignkey')
    op.create_foreign_key('wishlists_product_id_fkey', 'wishlists', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('wishlists_user_id_fkey', 'wishlists', 'user_profiles', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'user_profiles', schema='public', type_='foreignkey')
    op.create_foreign_key('user_profiles_user_id_fkey', 'user_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'products', schema='public', type_='foreignkey')
    op.create_foreign_key('products_category_id_fkey', 'products', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'product_reviews', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'product_reviews', schema='public', type_='foreignkey')
    op.create_foreign_key('product_reviews_product_id_fkey', 'product_reviews', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('product_reviews_user_id_fkey', 'product_reviews', 'user_profiles', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'payments', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'payments', schema='public', type_='foreignkey')
    op.create_foreign_key('payments_order_id_fkey', 'payments', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('payments_user_id_fkey', 'payments', 'user_profiles', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'orders', schema='public', type_='foreignkey')
    op.create_foreign_key('orders_user_id_fkey', 'orders', 'user_profiles', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'inventory', schema='public', type_='foreignkey')
    op.create_foreign_key('inventory_product_id_fkey', 'inventory', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'carts', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'carts', schema='public', type_='foreignkey')
    op.create_foreign_key('carts_product_id_fkey', 'carts', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('carts_user_id_fkey', 'carts', 'user_profiles', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'cart_items', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'cart_items', schema='public', type_='foreignkey')
    op.create_foreign_key('cart_items_product_id_fkey', 'cart_items', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('cart_items_cart_id_fkey', 'cart_items', 'carts', ['cart_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'addresses', schema='public', type_='foreignkey')
    op.create_foreign_key('addresses_user_profile_id_fkey', 'addresses', 'user_profiles', ['user_profile_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
